import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "./components/Navbar";
// import './link.css'
//import Link from "next/link";
// import { usePathname } from 'next/navigation'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const pathname = usePathname()
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}      >
        <div id="header">
          <h1>Header</h1>
          <hr />
          {/* Nav Bar */}
          <NavBar/>
        </div>
        <hr />
        {children}
        <hr />
        <div>
          <footer>
            <h2>Footer</h2>
          </footer>
        </div>
      </body>
    </html>
  );
}
