import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}      >
        <div id="header">
          <h1>Header</h1>
          <hr />
          {/* Nav Bar */}
          <nav>
            <ul>
              <li><Link href={{ pathname: '/' }}>Home</Link></li>
              <li><Link href={{ pathname: '/history' }}>history</Link></li>
            </ul>

          </nav>
        </div>
        <hr />
        {children}
        <hr />
        <div>
          <footer>
            <h2>Footer</h2>
          </footer>
        </div>
      </body>
    </html>
  );
}
